add heading*, speed*, fix type and number of satelites
HaydenAI/telegraf pull request #14
Opened 2023-07-21 10:18 UTC by andrejlevkovitch

### Required for all PRs:

- [ ] Signed [CLA](https://influxdata.com/community/cla/).
- [ ] Associated README.md updated.
- [ ] Has appropriate unit tests.

2023-07-21 10:20 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox-reader.go
> +	TimeOnlyFix                uint8 = 5
@anycmon fix type meaning

2023-07-21 11:58 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
@anycmon [see this example](https://github.com/HaydenAI/ublox-utils/blob/f9d065b7a40efa3404740d32cbdabeda6b946d25/sample/data-printer.cpp#L376-L423) how convert that values to something readable

2023-07-21 11:59 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
or look at ESF_STATUS in "ZED-F9R InterfaceDescription.pd"

2023-07-21 15:18 UTC, SWang525 reviewed
LGTM on the parsing side except for one question for me to understand. I did not check `go` files

2023-07-21 15:18 UTC, SWang525 commented on plugins/inputs/ublox/ublox-reader.cpp
> +                 4 * esf_status->payload.numSens);
To help me understand, are these lines for getting the calibration status of accel, gyro and single tick (7 channel in total, the ones we showed in GUI)?

2023-07-21 18:16 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox-reader.cpp
> +                 4 * esf_status->payload.numSens);
yes

2023-07-21 18:22 UTC, SWang525 approved these changes

2023-09-21 07:01 UTC, TPiowczykHay reviewed
To sum up, these inputs are new and need to be added to proto file to be caught:
```
float64 horizontal_acc
float64 heading_of_motion
float64 heading_acc
bool    heading_is_valid
float64 speed
float64 speed_acc
uint32  sat_num
uint32  fix_type // 0-5 enum 

uint32 s1_status1 // Used = 0b01000000, Ready = 0b10000000
uint32 s1_status2 // NotCalibrated = 0b0000, Calibrating = 0b0001, Calibrated1 = 0b0010, Calibrated2 = 0b0011
uint32 s1_freq    // number
uint32 s1_faults  // BadMeas = 0b0001, BadTTag = 0b0010, MissingMeas = 0b0100, NoisyMeas = 0b1000
...
uint32 s2_status1
uint32 s2_status2
uint32 s2_freq
uint32 s2_faults
...
```
So, the proto file needs a static type for sensors, how many sensors should we add? This is kind of awkward to me that we would need to define statically the amount of sensors..

I guess we can merge it freely before proto changes (and influx proto proxy) or was there any note from Marcin that it needs to be synced?

2023-09-21 09:27 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox.go
> +		}
@andrejlevkovitch continuing about the sensors:

I don't like it, if there are 7 sensors, there is 49 fields to be added to each influx gps record. 
If it would grow we would need another 4 fields to support it.
I'm not sure if there is a better solution though, hmm there is somewhat similar case in telegraf already - on smart_attribute (which is basically extension to `smart` metric) `Temperature Sensor 1` - there are up to 8 sensors, but they're just name, meaning the schema is 
```
string name
int32 value
...
```

I guess we could do something similar

```
gps_sensor

string name
uint32 s1_status1
uint32 s1_status2
uint32 s1_freq
uint32 s1_faults
```

But I don't know how complex it would be to separate these metrics

2023-09-21 09:43 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
Up to you. But from ublox perspective each sensor is described just with [4 bytes](https://github.com/HaydenAI/ublox-utils/blob/f9d065b7a40efa3404740d32cbdabeda6b946d25/include/ubx.h#L209-L215)

2023-09-21 09:49 UTC, TPiowczykHay commented
Update `plugins/inputs/ublox/README.md` please

2023-09-21 09:51 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox.go
> +		}
If we would up to separate it, then there is probably a change needed in `func (s *UbloxDataCollector) Gather(acc telegraf.Accumulator) error`
The sensors would not be put to `acc.AddFields("ublox-data", metrics, nil)` but to `acc.AddFields("ublox-data-sensors", metrics, nil)`

2023-09-21 10:02 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
Any reason to do that?

2023-09-21 10:09 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox.go
> +		}
Because this is the only place we can separate these metrics to avoid mentioned problem of cumbersome sensors fields

2023-09-21 10:19 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
Ok, so what exactly I should to do? Just move sensors data to `ublox-data-sensors`? Is that all?

2023-09-21 10:33 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox.go
> +		}
Yes, as far as I can see it's done on `smart_device` and `smart_attribute` example, this is the only change needed, then we'll be able to catch it as separate metric in `proto.go` to process

2023-09-21 10:46 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
done

2023-09-21 11:27 UTC, TPiowczykHay requested changes

2023-09-21 11:27 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox.go
> +		}
As far as it'll be added to new metric it will not solve the huge amount of fields. Let's change the schema:
```suggestion
		for i := 0; i*4 < len(s.lastPos.Sensors); i++ {
			tags := map[string]interface{}{ "name": fmt.Sprintf("Sensor %d", i)}

			sensors["s_status1"] = s.lastPos.Sensors[i*4+0]
			sensors["s_status2"] = s.lastPos.Sensors[i*4+1]
			sensors["s_freq"] = s.lastPos.Sensors[i*4+2]
			sensors["s_faults"] = s.lastPos.Sensors[i*4+3]

			acc.AddFields("ublox-data-sensors", sensors, tags)
		}
```

It'd be worth to start writing tests for such changes
They're not hard to write - some test examples are there `plugins/inputs/smart/smart_test.go`

2023-09-21 11:39 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
could you make that changes?

2023-09-21 12:16 UTC, TPiowczykHay commented
@andrejlevkovitch I've tried to add test for ublox.go but the cpp files does not compile in my IDE, so I'll leave it to you

> It'd be worth to start writing tests for such changes
They're not hard to write - some test examples are there plugins/inputs/smart/smart_test.go

2023-09-21 13:00 UTC, andrejlevkovitch commented
> I've tried to add test for ublox.go but the cpp files does not compile in my IDE

So, what problem you have with compiling it?

Also I see that there are still request change for that pr. Do you steal have some requested changes, or you just forgot to cancel previous request?

2023-09-21 13:05 UTC, TPiowczykHay commented
> So, what problem you have with compiling it?

Goland throws out this output:
```
# github.com/influxdata/telegraf/plugins/inputs/ublox [github.com/influxdata/telegraf/plugins/inputs/ublox.test]
In file included from ublox-reader.cpp:1:
In file included from ./ublox-utils/include/ublox_reader.h:3:
./ublox-utils/include/ublox_parser.h:7:16: warning: alias declarations are a C++11 extension [-Wc++11-extensions]
ublox-reader.cpp:68:23: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
ublox-reader.cpp:81:47: error: expected ';' after expression
ublox-reader.cpp:81:47: warning: multi-character character constant [-Wmultichar]
ublox-reader.cpp:81:52: error: expected ';' after expression
ublox-reader.cpp:82:47: error: expected ';' after expression
ublox-reader.cpp:82:47: warning: multi-character character constant [-Wmultichar]
ublox-reader.cpp:82:52: error: expected ';' after expression
ublox-reader.cpp:84:58: warning: missing terminating ' character [-Winvalid-pp-token]
ublox-reader.cpp:86:56: warning: missing terminating ' character [-Winvalid-pp-token]
ublox-reader.cpp:87:63: warning: missing terminating ' character [-Winvalid-pp-token]
ublox-reader.cpp:88:60: warning: missing terminating ' character [-Winvalid-pp-token]
ublox-reader.cpp:92:51: warning: missing terminating ' character [-Winvalid-pp-token]
ublox-reader.cpp:93:53: warning: missing terminating ' character [-Winvalid-pp-token]
ublox-reader.cpp:84:9: error: unterminated function-like macro invocation
ublox-reader.cpp:8:9: note: macro 'TRY_SET' defined here
ublox-reader.cpp:127:2: error: expected '}'
ublox-reader.cpp:77:54: note: to match this '{'
ublox-reader.cpp:127:2: error: expected '}'
ublox-reader.cpp:67:66: note: to match this '{'
ublox-reader.cpp:67:13: warning: enumeration value 'Error' not handled in switch [-Wswitch]
ublox-reader.cpp:67:13: note: add missing switch cases
ublox-reader.cpp:127:2: error: expected '}'
ublox-reader.cpp:66:12: note: to match this '{'
ublox-reader.cpp:127:2: error: expected '}'
ublox-reader.cpp:60:42: note: to match this '{'
ublox-reader.cpp:81:47: warning: expression result unused [-Wunused-value]
ublox-reader.cpp:10:12: note: expanded from macro 'TRY_SET'
ublox-reader.cpp:81:52: warning: expression result unused [-Wunused-value]
ublox-reader.cpp:10:12: note: expanded from macro 'TRY_SET'
ublox-reader.cpp:82:47: warning: expression result unused [-Wunused-value]
ublox-reader.cpp:10:12: note: expanded from macro 'TRY_SET'
ublox-reader.cpp:82:52: warning: expression result unused [-Wunused-value]
ublox-reader.cpp:10:12: note: expanded from macro 'TRY_SET'
ublox-reader.cpp:127:2: error: expected '}'
ublox-reader.cpp:14:12: note: to match this '{'

Compilation finished with exit code 1
``` 

> Also I see that there are still request change for that pr. Do you steal have some requested changes, or you just forgot to cancel previous request?

Could you include mentioned tests?

2023-09-21 14:09 UTC, andrejlevkovitch commented
> Could you include mentioned tests?

If I didn't miss anything, you only mentioned that: `It'd be worth to start writing tests for such changes` - I have no idea what exactly you want to test

2023-09-21 17:20 UTC, TPiowczykHay commented
> I don't understand why you try to compile ublox-reader.cpp

This is go compilation that involves this file for unknown reason to me.

> I have no idea what exactly you want to test

The correctness of data scheme accumulated to telegraf to assert if metrics are correctly separated and aligned. Similar as in the mentioned example tests https://github.com/HaydenAI/telegraf/blob/96ebba1a757a02446274b57bbef55a19427e3d09/plugins/inputs/smart/smart_test.go#L1

2023-09-21 17:41 UTC, andrejlevkovitch commented
@TPiowczykHay If you want to add that tests - please go ahead. Don't wait that from me. I am not a go developer, and I (as device team) don't support telegraf. And I have a lot of different things on my plate. The code and build is absolutely working, if you have a problem with IDE - it is not my problems. I use `vim` for example and have no problems - can recommend it to you

2023-10-04 11:34 UTC, anycmon commented on plugins/inputs/ublox/ublox.go
> +		}
Ideally this plugin extract all data, we can filter what we push to cloud in telegraf configuration. Do we need all of them in cloud?

2023-10-04 11:46 UTC, anycmon commented
@TPiowczykHay building it on Mac is complicated but we can setup build on nx [GH nodes](https://github.com/HaydenAI/ABLE2/blob/main/.github/workflows/pr.yml#L19) so it should works.

2023-10-04 11:52 UTC, anycmon commented on plugins/inputs/ublox/ublox.go
> +		}
> or look at ESF_STATUS in "ZED-F9R InterfaceDescription.pd"

@andrejlevkovitch where is this file?

2023-10-04 11:55 UTC, anycmon commented on plugins/inputs/ublox/ublox-reader.go
> +	Sensors    []byte
Can we make it int or uint? I don't think so grafana or influxdb supports byte.

2023-10-04 11:56 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
I'm not sure where it is in the cloud, so look here:
[ZED-F9R InterfaceDescription.pdf](https://github.com/HaydenAI/telegraf/files/12802966/ZED-F9R.InterfaceDescription.pdf)

2023-10-04 11:57 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
> Do we need all of them in cloud?

This is probably question to @SWang525

2023-10-04 12:05 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox-reader.go
> +	Sensors    []byte
Probably you missed that it is internal structure - we don't expose it. See [here](https://github.com/HaydenAI/telegraf/blob/a36805010c0dd6c3e411371f20f5717443ebd701/plugins/inputs/ublox/ublox.go#L107-L116) for metrics collection

2023-10-04 12:11 UTC, TPiowczykHay commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
In current implementation it's:
```suggestion
Provide `ublox-data-sensors` with next fields:

- `s_status1`  - byte
- `s_status2`  - byte
- `s_freq`     - byte
- `s_faults`   - byte

and next tags:

-  `name` - string
```

2023-10-04 12:14 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox-reader.go
> +	Sensors    []byte
The array as a whole not, but it's exposed as single byte for each sensor field.
Grafana supports byte data type, not sure about influx

2023-10-04 12:18 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox-reader.go
> +	Sensors    []byte
I see, but between the plugin and influxdb we also serialize it to protobuf - I thought we decide type there, isn't it?

2023-10-04 12:22 UTC, andrejlevkovitch commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
what is the `name`?

2023-10-04 12:29 UTC, TPiowczykHay commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
Unique identifier for particular sensor that also contains the sensor number

2023-10-05 12:23 UTC, anycmon commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
+1, it would be easier to search for particular sensor instead of some regex or pattern matching

2023-10-05 12:48 UTC, TPiowczykHay commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
This is the same as `smart` with `smart_attributes` are designed.
- Maintainability of the amount of sensors - since now we got 7 and that's something that can potentially change, currently it'd add 28 new fields (4x7) to each record (and we would need to explicitly add that amount to proto). When sensor number changes you need to:
  - change the code to support new sensor
  - rewrite aggregation queries to support new sensor
- When you define static number of sensors, you will get into many operations limitation on influx when e.g comparing multiple sensors for each device while one could have it empty - it can return invalid no data
- Tedious hardcoding or transformations if want to select only particular field (like `sN_status1`)
- Some queries can output unexpected results when the number of sensors are different between devices

While tagged by name, you don't have to change code when number of sensors changes, you don't have 28 new (empty or not) field on each record. You

> instead of some regex or pattern matching

I think more often we use aggregation and grouping would like to use * `SELECT * FROM sensors GROUP BY name` would be easier than writing all the 28 fields in select.
In some scenario it may be easier to have separate field, but we would lose too many benefits

> Could you explain that one?

Hope this example influx query would explain more:
`SELECT * FROM 'ublox-data-sensors' GROUP BY name` 
that would output:
```
[
    {
        "name": "Sensor 1",
        "s_status1": "..",
        "s_status2": "..",
        "s_freq": "..",
        "s_faults": ".."
    },
    {
        "name": "Sensor 2",
        "s_status1": "..",
        "s_status2": "..",
        "s_freq": "..",
        "s_faults": ".."
    }
]
```
while in previous version we would need to make:
`SELECT s1_status1, s1_status2, s1_freq, s1_faults, s2_status1, s2_status2, s2_freq, s2_faults FROM 'ublox-data-sensors'` 
that would output
```
[
    {
        "s1_status1": "..",
        "s1_status2": "..",
        "s1_freq": "..",
        "s1_faults": "..",
        "s2_status1": "..",
        "s2_status2": "..",
        "s2_freq": "..",
        "s2_faults": ".."
    },
]
```

2023-10-05 13:16 UTC, andrejlevkovitch commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
Ok, now I see what you mean. Anyway, I see that you already made related changes to that pr... Are you sure that you did that correctly? I mean: adding fields to the metrics. That doesn't look correct

2023-10-05 13:16 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
@TPiowczykHay are you sure about doing that in the loop?

2023-10-05 16:47 UTC, TPiowczykHay commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
> I mean: adding fields to the metrics. That doesn't look correct

What do you mean?

2023-10-05 16:52 UTC, TPiowczykHay commented on plugins/inputs/ublox/ublox.go
> +		}
`acc.AddFields` can be confusing in naming, but while you look at comment it's more clear that it adds separate metric
```
// AddFields adds a metric to the accumulator with the given measurement
	// name, fields, and tags (and timestamp). If a timestamp is not provided,
	// then the accumulator sets it to "now".
	AddFields(...)
```
Which is what I wish to be to achieve described schema

This will basically add 7 records to `ublox-data-sensors` for each `ublox-data` record. This is the same logic as in `smart` -> `smart_attribute` metrics

2023-10-06 09:58 UTC, andrejlevkovitch commented on plugins/inputs/ublox/ublox.go
> +		}
OK, I see now, thanks

2023-10-06 09:59 UTC, andrejlevkovitch commented on plugins/inputs/ublox/README.md
> +- `s{N}_faults`   - byte
never mind, I already saw your explanation bellow

2023-10-06 09:59 UTC, andrejlevkovitch commented
@TPiowczykHay @anycmon are there any other issues that are not resolved?

2024-01-05 01:54 UTC, thien-nguyen-fw approved these changes
Looks good to me.

2024-01-05 10:18 UTC, merged